import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import MoneyInput, { parseMoney, formatTRY } from './MoneyInput';

const PAYMENT_KEY='@gelir_giderim_payments_v1';
const C={bg:'#0B1020',card:'#141B2D',card2:'#101726',border:'#263149',text:'#F5F7FB',muted:'#95A2B8',income:'#2DD4A7',expense:'#FF6B6B',accent:'#6EA8FE',warning:'#FBBF24'};
const pad=(n)=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;};
const monthKey=(d)=>String(d||'').slice(0,7);
const pretty=(iso)=>{const[y,m,d]=String(iso||'').split('-');return y&&m&&d?`${d}.${m}.${y}`:iso;};
const LABEL={fixed:'Sabit Ödeme',loan:'Kredi',person:'Kişiye Borç',pending:'Bekleyen Ödeme'};

function Chip({label,active,onPress}){return <Pressable onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&{color:C.accent}]}>{label}</Text></Pressable>;}

export default function Payments({onAddExpense,onRemoveExpense}){
  const [payments,setPayments]=useState([]),[loaded,setLoaded]=useState(false),[kind,setKind]=useState('fixed'),[name,setName]=useState(''),[amount,setAmount]=useState(''),[dueDay,setDueDay]=useState('1'),[remaining,setRemaining]=useState(''),[dueDate,setDueDate]=useState(today()),[filter,setFilter]=useState('waiting');
  const month=monthKey(today());
  useEffect(()=>{AsyncStorage.getItem(PAYMENT_KEY).then((x)=>setPayments(x?JSON.parse(x):[])).catch(()=>{}).finally(()=>setLoaded(true));},[]);
  useEffect(()=>{if(loaded)AsyncStorage.setItem(PAYMENT_KEY,JSON.stringify(payments)).catch(()=>{});},[payments,loaded]);

  const data=useMemo(()=>payments.filter((x)=>x.kind!=='bill'),[payments]);
  const isPaid=(p)=>(p.kind==='fixed'||p.kind==='loan')?Boolean(p.paidPeriods?.[month]):Boolean(p.paidAt);
  const visible=useMemo(()=>[...data].filter((p)=>filter==='all'?true:filter==='paid'?isPaid(p):!isPaid(p)).sort((a,b)=>{const ad=(a.kind==='fixed'||a.kind==='loan')?`${month}-${pad(a.dueDay||1)}`:(a.dueDate||'9999');const bd=(b.kind==='fixed'||b.kind==='loan')?`${month}-${pad(b.dueDay||1)}`:(b.dueDate||'9999');return ad.localeCompare(bd);}),[data,filter,month]);
  const loanRemaining=useMemo(()=>data.filter((p)=>p.kind==='loan').reduce((sum,p)=>sum+Number(p.amount||0)*Number(p.remainingInstallments||0),0),[data]);
  const waitingTotal=useMemo(()=>data.filter((p)=>!isPaid(p)).reduce((sum,p)=>sum+Number(p.amount||0),0),[data,month]);

  const add=()=>{const v=parseMoney(amount);if(!name.trim())return Alert.alert('Ad gerekli','Ödeme için bir ad yaz.');if(v<=0)return Alert.alert('Tutar gerekli','0’dan büyük bir tutar gir.');const base={id:`pay_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,kind,name:name.trim(),amount:v,createdAt:Date.now()};if(kind==='fixed'||kind==='loan'){const d=Number(dueDay);if(d<1||d>31)return Alert.alert('Gün hatalı','1-31 arasında gün gir.');base.dueDay=d;base.paidPeriods={};}if(kind==='loan'){const r=Number(remaining);if(r<=0)return Alert.alert('Taksit gerekli','Kalan taksit sayısını gir.');base.remainingInstallments=r;}if(kind==='person'||kind==='pending'){if(!/^\d{4}-\d{2}-\d{2}$/.test(dueDate))return Alert.alert('Tarih hatalı','YYYY-AA-GG biçiminde tarih gir.');base.dueDate=dueDate;base.paidAt=null;}setPayments((old)=>[base,...old]);setName('');setAmount('');setRemaining('');};

  const toggle=(p)=>{const recurring=p.kind==='fixed'||p.kind==='loan',period=recurring?month:'once',paid=isPaid(p);if(paid){setPayments((old)=>old.map((x)=>{if(x.id!==p.id)return x;if(recurring){const n={...(x.paidPeriods||{})};delete n[month];return {...x,paidPeriods:n,remainingInstallments:x.kind==='loan'?Number(x.remainingInstallments||0)+1:x.remainingInstallments};}return {...x,paidAt:null};}));onRemoveExpense?.(p.id,period);return;}if(p.kind==='loan'&&Number(p.remainingInstallments||0)<=0)return Alert.alert('Kredi tamamlandı','Kalan taksit görünmüyor.');setPayments((old)=>old.map((x)=>x.id===p.id?(recurring?{...x,paidPeriods:{...(x.paidPeriods||{}),[month]:today()},remainingInstallments:x.kind==='loan'?Math.max(0,Number(x.remainingInstallments||0)-1):x.remainingInstallments}:{...x,paidAt:today()}):x));onAddExpense?.({sourcePaymentId:p.id,paymentPeriod:period,amount:Number(p.amount||0),category:p.kind==='fixed'?'Kira':'Borç',note:p.name,date:today()});};
  const remove=(p)=>Alert.alert('Kaydı sil',`${p.name} silinsin mi?`,[{text:'Vazgeç',style:'cancel'},{text:'Sil',style:'destructive',onPress:()=>setPayments((old)=>old.filter((x)=>x.id!==p.id))}]);

  return <View style={s.wrap}>
    <View style={s.summaryRow}><View style={s.summary}><Text style={s.small}>BEKLEYEN</Text><Text style={[s.sumValue,{color:C.warning}]}>{formatTRY(waitingTotal)}</Text></View><View style={s.summary}><Text style={s.small}>KREDİ KALAN</Text><Text style={[s.sumValue,{color:C.accent}]}>{formatTRY(loanRemaining)}</Text></View></View>
    <View style={s.card}><Text style={s.cardTitle}>Ödeme / borç ekle</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rowGap}><Chip label="Sabit / Kira" active={kind==='fixed'} onPress={()=>setKind('fixed')}/><Chip label="Kredi" active={kind==='loan'} onPress={()=>setKind('loan')}/><Chip label="Kişiye Borç" active={kind==='person'} onPress={()=>setKind('person')}/><Chip label="Bekleyen" active={kind==='pending'} onPress={()=>setKind('pending')}/></ScrollView>
      <Text style={s.label}>{kind==='person'?'Kime borçlusun?':'Ödeme adı'}</Text><TextInput value={name} onChangeText={setName} placeholder={kind==='fixed'?'Örn. Ev kirası':kind==='loan'?'Örn. İhtiyaç kredisi':kind==='person'?'Örn. Ahmet':'Örn. Servis ödemesi'} placeholderTextColor={C.muted} style={s.input}/>
      <MoneyInput label={kind==='loan'?'Aylık taksit':'Tutar'} value={amount} onChangeText={setAmount}/>
      {(kind==='fixed'||kind==='loan')&&<><Text style={s.label}>Her ay ödeme günü</Text><TextInput value={dueDay} onChangeText={setDueDay} keyboardType="number-pad" placeholder="1" placeholderTextColor={C.muted} style={s.input}/></>}
      {kind==='loan'&&<><Text style={s.label}>Kalan taksit</Text><TextInput value={remaining} onChangeText={setRemaining} keyboardType="number-pad" placeholder="18" placeholderTextColor={C.muted} style={s.input}/></>}
      {(kind==='person'||kind==='pending')&&<><Text style={s.label}>Son ödeme tarihi</Text><TextInput value={dueDate} onChangeText={setDueDate} placeholder="YYYY-AA-GG" placeholderTextColor={C.muted} style={s.input}/></>}
      <Pressable onPress={add} style={s.primary}><Text style={s.primaryText}>Kaydet</Text></Pressable><Text style={s.hint}>Planlanan ödeme İşlemler’de görünmez. “Ödendi” dediğinde gider olarak otomatik eklenir.</Text>
    </View>
    <View style={s.filter}><Chip label="Bekleyen" active={filter==='waiting'} onPress={()=>setFilter('waiting')}/><Chip label="Ödendi" active={filter==='paid'} onPress={()=>setFilter('paid')}/><Chip label="Tümü" active={filter==='all'} onPress={()=>setFilter('all')}/></View>
    {!visible.length?<View style={s.empty}><Text style={s.emptyTitle}>Kayıt yok</Text><Text style={s.hint}>Kira, kredi veya borç ekleyebilirsin.</Text></View>:visible.map((p)=>{const paid=isPaid(p),loan=p.kind==='loan';return <View key={p.id} style={[s.item,paid&&{borderColor:'rgba(45,212,167,.45)'}]}><Pressable onLongPress={()=>remove(p)} style={{flex:1}}><View style={s.itemHead}><Text style={s.kind}>{LABEL[p.kind]||'Ödeme'}</Text><Text style={[s.status,{color:paid?C.income:C.warning}]}>{paid?'ÖDENDİ':'BEKLİYOR'}</Text></View><Text style={s.name}>{p.name}</Text><Text style={s.meta}>{p.kind==='fixed'?`Her ay ${p.dueDay}. gün`:loan?`${p.remainingInstallments||0} taksit kaldı · Kalan ${formatTRY(Number(p.amount||0)*Number(p.remainingInstallments||0))}`:`Son ödeme ${pretty(p.dueDate)}`}</Text><Text style={s.amount}>{formatTRY(p.amount)}</Text><Text style={s.hint}>Basılı tut: sil</Text></Pressable><Pressable onPress={()=>toggle(p)} style={[s.pay,paid&&s.undo]}><Text style={[s.payText,paid&&{color:C.muted}]}>{paid?'Geri al':'Ödendi'}</Text></Pressable></View>;})}
  </View>;
}

const s=StyleSheet.create({wrap:{gap:14},summaryRow:{flexDirection:'row',gap:10},summary:{flex:1,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14},small:{color:C.muted,fontSize:9,fontWeight:'900'},sumValue:{fontSize:16,fontWeight:'900',marginTop:7},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:20,padding:16,gap:10},cardTitle:{color:C.text,fontSize:18,fontWeight:'900'},rowGap:{gap:7,paddingVertical:2},chip:{backgroundColor:C.card2,borderWidth:1,borderColor:C.border,borderRadius:999,paddingHorizontal:12,paddingVertical:8},chipActive:{borderColor:C.accent,backgroundColor:'rgba(110,168,254,.13)'},chipText:{color:C.muted,fontSize:11,fontWeight:'800'},label:{color:C.muted,fontSize:11,fontWeight:'800'},input:{backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:14,color:C.text,paddingHorizontal:14,paddingVertical:12},primary:{backgroundColor:C.accent,borderRadius:14,paddingVertical:13,alignItems:'center'},primaryText:{color:'#071016',fontWeight:'900'},hint:{color:C.muted,fontSize:10,lineHeight:15},filter:{flexDirection:'row',gap:7,flexWrap:'wrap'},empty:{borderWidth:1,borderStyle:'dashed',borderColor:C.border,borderRadius:18,padding:22,alignItems:'center'},emptyTitle:{color:C.text,fontWeight:'900'},item:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',gap:10},itemHead:{flexDirection:'row',justifyContent:'space-between'},kind:{color:C.accent,fontSize:9,fontWeight:'900'},status:{fontSize:9,fontWeight:'900'},name:{color:C.text,fontSize:15,fontWeight:'900',marginTop:4},meta:{color:C.muted,fontSize:10,marginTop:3},amount:{color:C.text,fontSize:18,fontWeight:'900',marginTop:7},pay:{backgroundColor:C.income,borderRadius:12,paddingHorizontal:12,paddingVertical:10},undo:{backgroundColor:C.card2,borderWidth:1,borderColor:C.border},payText:{color:'#071016',fontSize:11,fontWeight:'900'}});
