import React,{useEffect,useMemo,useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import MoneyInput,{parseMoney,formatTRY}from'./MoneyInput';

const KEY='@abi_butce_rentals_v1';
const ECONOMY_URL='https://raw.githubusercontent.com/ataalkis/metadigital/main/gelir-giderim/content/economy.json';
const C={bg:'#0B1020',card:'#141B2D',card2:'#101726',border:'#263149',text:'#F5F7FB',muted:'#95A2B8',accent:'#6EA8FE',income:'#2DD4A7',expense:'#FF6B6B',warning:'#FBBF24'};
const MONTHS=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const currentYear=()=>new Date().getFullYear();
const nextIncreaseDate=(month)=>{const now=new Date(),m=Math.min(12,Math.max(1,Number(month||1)));let y=now.getFullYear();const target=new Date(y,m-1,1);if(target<new Date(now.getFullYear(),now.getMonth(),1))y++;return`${y}-${pad(m)}-01`};

function Chip({label,active,onPress}){return<Pressable onPress={onPress} style={[s.chip,active&&s.chipActive]}><Text style={[s.chipText,active&&{color:C.accent}]}>{label}</Text></Pressable>}

export default function Rentals({onAddTransaction,onRemoveTransaction}){
 const[items,setItems]=useState([]),[loaded,setLoaded]=useState(false),[direction,setDirection]=useState('expense'),[title,setTitle]=useState(''),[party,setParty]=useState(''),[amount,setAmount]=useState(''),[increaseMonth,setIncreaseMonth]=useState(String(new Date().getMonth()+1)),[increaseRate,setIncreaseRate]=useState(''),[year,setYear]=useState(currentYear()),[selectedId,setSelectedId]=useState(null),[economy,setEconomy]=useState(null);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>setItems(x?JSON.parse(x):[])).catch(()=>{}).finally(()=>setLoaded(true))},[]);
 useEffect(()=>{fetch(`${ECONOMY_URL}?t=${Date.now()}`,{headers:{'Cache-Control':'no-cache'}}).then(r=>r.ok?r.json():null).then(x=>{if(x)setEconomy(x)}).catch(()=>{})},[]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem(KEY,JSON.stringify(items)).catch(()=>{})},[items,loaded]);
 const years=useMemo(()=>{const ys=new Set([currentYear(),currentYear()-1]);items.forEach(x=>Object.keys(x.periods||{}).forEach(p=>ys.add(Number(p.slice(0,4)))));return[...ys].sort((a,b)=>b-a)},[items]);
 const officialRate=Number(economy?.tufe12MonthAverage||0);
 const save=()=>{const v=parseMoney(amount),m=Number(increaseMonth),typed=String(increaseRate||'').trim(),r=Number(typed.replace(',','.'));if(!title.trim())return Alert.alert('Ad gerekli','Örn. Ev kirası veya Kadıköy daire yaz.');if(v<=0)return Alert.alert('Tutar gerekli','Aylık kira tutarını gir.');if(m<1||m>12)return Alert.alert('Artış ayı','1-12 arasında bir ay gir.');setItems(old=>[{id:`rent_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,direction,title:title.trim(),party:party.trim(),amount:v,increaseMonth:m,useOfficialRate:!typed,increaseRate:typed&&Number.isFinite(r)?r:0,periods:{},createdAt:Date.now()},...old]);setTitle('');setParty('');setAmount('');setIncreaseRate('')};
 const togglePeriod=(x,monthIndex)=>{const period=`${year}-${pad(monthIndex+1)}`,existing=x.periods?.[period];if(existing){setItems(old=>old.map(r=>{if(r.id!==x.id)return r;const next={...(r.periods||{})};delete next[period];return{...r,periods:next}}));onRemoveTransaction?.(x.id,period);return}const entry={amount:Number(x.amount||0),date:today()};setItems(old=>old.map(r=>r.id===x.id?{...r,periods:{...(r.periods||{}),[period]:entry}}:r));onAddTransaction?.({sourcePaymentId:x.id,paymentPeriod:period,type:x.direction==='income'?'income':'expense',amount:entry.amount,category:x.direction==='income'?'Kira Geliri':'Kira',note:x.title,date:entry.date})};
 const paidTotal=(x)=>Object.entries(x.periods||{}).filter(([p])=>p.startsWith(`${year}-`)).reduce((sum,[,v])=>sum+Number(v.amount||0),0);
 const rateFor=(x)=>x.useOfficialRate?officialRate:Number(x.increaseRate||0);
 const projected=(x)=>{const r=rateFor(x);return r>0?Number(x.amount||0)*(1+r/100):null};
 return<View style={s.wrap}>
  <View><Text style={s.title}>Kira Takibi</Text><Text style={s.sub}>Ödediğin kiraları ve kiraya verdiğin yerlerden aldığın kiraları yıllara göre takip et.</Text></View>
  {!!officialRate&&<View style={s.cpi}><View><Text style={s.small}>GÜNCEL TÜFE · 12 AYLIK ORTALAMA</Text><Text style={s.cpiValue}>%{officialRate.toFixed(2).replace('.',',')}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.cpiPeriod}>{economy?.period||''}</Text><Text style={s.cpiSource}>{economy?.source||'TÜİK'}</Text></View></View>}
  <View style={s.card}><Text style={s.cardTitle}>Yeni kira kaydı</Text><View style={s.segment}><Pressable onPress={()=>setDirection('expense')} style={[s.seg,direction==='expense'&&s.segExpense]}><Text style={{color:direction==='expense'?C.expense:C.muted,fontWeight:'900'}}>Ödediğim Kira</Text></Pressable><Pressable onPress={()=>setDirection('income')} style={[s.seg,direction==='income'&&s.segIncome]}><Text style={{color:direction==='income'?C.income:C.muted,fontWeight:'900'}}>Aldığım Kira</Text></Pressable></View>
   <Text style={s.label}>Kayıt adı</Text><TextInput value={title} onChangeText={setTitle} placeholder={direction==='income'?'Örn. Üsküdar daire':'Örn. Ev kirası'} placeholderTextColor={C.muted} style={s.input}/>
   <Text style={s.label}>{direction==='income'?'Kiracı / açıklama':'Ev sahibi / açıklama'}</Text><TextInput value={party} onChangeText={setParty} placeholder="Opsiyonel" placeholderTextColor={C.muted} style={s.input}/>
   <MoneyInput label="Aylık kira" value={amount} onChangeText={setAmount}/>
   <Text style={s.label}>Kira artış ayı</Text><TextInput value={increaseMonth} onChangeText={setIncreaseMonth} keyboardType="number-pad" placeholder="11" placeholderTextColor={C.muted} style={s.input}/>
   <Text style={s.label}>Özel artış oranı (%) — opsiyonel</Text><TextInput value={increaseRate} onChangeText={setIncreaseRate} keyboardType="decimal-pad" placeholder={officialRate?`Boşsa güncel TÜFE %${officialRate.toFixed(2).replace('.',',')} kullanılır`:'Örn. 31,49'} placeholderTextColor={C.muted} style={s.input}/><Text style={s.hint}>Alanı boş bırakırsan uzaktan güncellenen güncel TÜFE oranı kullanılır. Yenileme ayı gelmeden önce gösterilen tutar tahmindir.</Text>
   <Pressable onPress={save} style={s.primary}><Text style={s.primaryText}>Kira Kaydını Oluştur</Text></Pressable>
  </View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{years.map(y=><Chip key={y} label={String(y)} active={year===y} onPress={()=>setYear(y)}/>)}</ScrollView>
  {!items.length?<View style={s.empty}><Text style={s.cardTitle}>Henüz kira kaydı yok</Text></View>:items.map(x=>{const proj=projected(x),r=rateFor(x);return<View key={x.id} style={s.rentCard}><Pressable onPress={()=>setSelectedId(selectedId===x.id?null:x.id)}><View style={s.head}><View style={{flex:1}}><Text style={[s.kind,{color:x.direction==='income'?C.income:C.expense}]}>{x.direction==='income'?'KİRA GELİRİ':'KİRA GİDERİ'}</Text><Text style={s.rentTitle}>{x.title}</Text>{!!x.party&&<Text style={s.meta}>{x.party}</Text>}</View><Text style={s.amount}>{formatTRY(x.amount)}</Text></View><View style={s.summary}><View><Text style={s.small}>{year} TOPLAM</Text><Text style={s.sum}>{formatTRY(paidTotal(x))}</Text></View><View><Text style={s.small}>SONRAKİ ARTIŞ</Text><Text style={s.sum}>{nextIncreaseDate(x.increaseMonth)}</Text></View></View>{proj&&<Text style={s.estimate}>{x.useOfficialRate?'Güncel TÜFE':'Girilen oran'} %{r.toFixed(2).replace('.',',')} ile bugünkü tahmini yeni kira: {formatTRY(proj)}</Text>}</Pressable>
   {selectedId===x.id&&<View style={s.monthGrid}>{MONTHS.map((m,i)=>{const p=`${year}-${pad(i+1)}`,done=Boolean(x.periods?.[p]);return<Pressable key={p} onPress={()=>togglePeriod(x,i)} style={[s.month,done&&s.monthDone]}><Text style={[s.monthText,done&&{color:C.income}]}>{m}</Text><Text style={s.monthMark}>{done?'✓':'○'}</Text></Pressable>})}</View>}
  </View>})}
 </View>
}

const s=StyleSheet.create({wrap:{gap:14},title:{color:C.text,fontSize:25,fontWeight:'900'},sub:{color:C.muted,fontSize:12,lineHeight:18,marginTop:4},cpi:{backgroundColor:C.card2,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cpiValue:{color:C.warning,fontSize:22,fontWeight:'900',marginTop:4},cpiPeriod:{color:C.text,fontSize:11,fontWeight:'900'},cpiSource:{color:C.muted,fontSize:9,marginTop:3},card:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:20,padding:16,gap:9},cardTitle:{color:C.text,fontSize:17,fontWeight:'900'},segment:{flexDirection:'row',backgroundColor:C.bg,borderRadius:14,padding:4,gap:4},seg:{flex:1,paddingVertical:10,borderRadius:11,alignItems:'center'},segExpense:{backgroundColor:'rgba(255,107,107,.14)'},segIncome:{backgroundColor:'rgba(45,212,167,.14)'},label:{color:C.muted,fontSize:11,fontWeight:'800'},input:{backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:14,color:C.text,paddingHorizontal:14,paddingVertical:12},hint:{color:C.muted,fontSize:10,lineHeight:15},primary:{backgroundColor:C.accent,borderRadius:14,paddingVertical:13,alignItems:'center'},primaryText:{color:'#071016',fontWeight:'900'},row:{gap:7},chip:{backgroundColor:C.card2,borderWidth:1,borderColor:C.border,borderRadius:999,paddingHorizontal:13,paddingVertical:8},chipActive:{borderColor:C.accent,backgroundColor:'rgba(110,168,254,.13)'},chipText:{color:C.muted,fontWeight:'800'},empty:{borderWidth:1,borderStyle:'dashed',borderColor:C.border,borderRadius:18,padding:22,alignItems:'center'},rentCard:{backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14,gap:10},head:{flexDirection:'row',gap:10,alignItems:'center'},kind:{fontSize:9,fontWeight:'900'},rentTitle:{color:C.text,fontSize:16,fontWeight:'900',marginTop:4},meta:{color:C.muted,fontSize:10,marginTop:3},amount:{color:C.text,fontSize:17,fontWeight:'900'},summary:{flexDirection:'row',justifyContent:'space-between',gap:12,backgroundColor:C.card2,borderRadius:14,padding:11},small:{color:C.muted,fontSize:8,fontWeight:'900'},sum:{color:C.text,fontSize:12,fontWeight:'900',marginTop:4},estimate:{color:C.warning,fontSize:10,fontWeight:'800'},monthGrid:{flexDirection:'row',flexWrap:'wrap',gap:7},month:{width:'23%',backgroundColor:C.card2,borderWidth:1,borderColor:C.border,borderRadius:12,paddingVertical:10,alignItems:'center'},monthDone:{borderColor:'rgba(45,212,167,.55)'},monthText:{color:C.muted,fontSize:10,fontWeight:'800'},monthMark:{color:C.muted,fontSize:15,marginTop:2}});
